### ISSUE TITLE
Error: group_humann2_uniref_abundances_to_go

### ISSUE THREAD

**Issue by subinamehta** [ASaiM/galaxytools#42]
@bebatut 
I ran the ASAIM workflow on usegalaxy.eu. The tool group_humann2_uniref_abundances_to_go gets completed but doesn't give an output apart from the header. I looked at the stderr and it showed me the error pasted below.

**Error:** 

>

> Traceback
> 
>  (most recent call last):
>   File "/usr/local/tools/_conda/envs/mulled-v1-9bc79a813cb75ba2c9ce416588a3693084acbc7c8949cf5154583f312deb663a/bin/map_to_slim.py", line 9, in <module>
>     from goatools.obo_parser import GODag
>   File "/usr/local/tools/_conda/envs/mulled-v1-9bc79a813cb75ba2c9ce416588a3693084acbc7c8949cf5154583f312deb663a/lib/python2.7/site-packages/goatools-0.6.4-py2.7.egg/goatools/__init__.py", line 5, in <module>
>   File "/usr/local/tools/_conda/envs/mulled-v1-9bc79a813cb75ba2c9ce416588a3693084acbc7c8949cf5154583f312deb663a/lib/python2.7/site-packages/goatools-0.6.4-py2.7.egg/goatools/go_enrichment.py", line 18, in <module>
>   File "/usr/local/tools/_conda/envs/mulled-v1-9bc79a813cb75ba2c9ce416588a3693084acbc7c8949cf5154583f312deb663a/lib/python2.7/site-packages/fisher/__init__.py", line 1, in <module>
>     from cfisher import *
>   File "numpy.pxd", line 148, in init cfisher (src/cfisher.c:5842)
> ValueError: numpy.dtype has the wrong size, try recompiling
> Loading table from: /data/dnb02/galaxy_db/files/007/507/dataset_7507949.dat
> Treating /data/dnb02/galaxy_db/files/007/507/dataset_7507949.dat as stratified output, e.g. ['UniRef50_A3DEF7', 'g__Clostridium.s__Clostridium_thermocellum']
> Loading custom groups file: tmp_data/uniref_go_mapping_output.txt
> Loading mapping file from: tmp_data/uniref_go_mapping_output.txt
> Original Feature Count: 4844; Grouped 1+ times: 2442 (%50.4); Grouped 2+ times: 1525 (%31.5)
> Loading table from: tmp_data/humann2_go_abundances.txt
> Treating tmp_data/humann2_go_abundances.txt as stratified output, e.g. ['GO:0000030', 'g__Clostridium.s__Clostridium_thermocellum']
> Loading custom groups file: tmp_data/formatted_humman2_go_slim.txt
> Loading mapping file from: tmp_data/formatted_humman2_go_slim.txt
> Original Feature Count: 516; Grouped 1+ times: 1 (%0.2); Grouped 2+ times: 0 (%0.0)
> Traceback (most recent call last):
>   File "/usr/local/tools/_conda/envs/mulled-v1-9bc79a813cb75ba2c9ce416588a3693084acbc7c8949cf5154583f312deb663a/bin/src/format_humann2_output.py", line 90, in <module>
>     format_humann2_output(args, go_annotations)
>   File "/usr/local/tools/_conda/envs/mulled-v1-9bc79a813cb75ba2c9ce416588a3693084acbc7c8949cf5154583f312deb663a/bin/src/format_humann2_output.py", line 66, in format_humann2_output
>     namespace = go_annotations[go_id]["namespace"]
> KeyError: 'UNGROUPED'

**Comment by subinamehta** [comment]
Hi ..do we have an update on the new version for Group Abundance tool!

**Comment by jraysajulga** [comment]
@bebatut It seems like you fixed this on your stand-alone tool as seen in this [commit](https://github.com/ASaiM/group_humann2_uniref_abundances_to_GO/commit/043fbbc2d3c06fa8dec77577ce4989fe7927e298). The issue here is that it has not been updated on the usegalaxy.eu dependency side. Reinstalling the tool might fix it.

For example:

Prior to 8/4/16, the `namespace = go_annotations[go_id]["namespace"]` code was on **line 66**.
```
humann2_output.py", line 66, in format_humann2_output
namespace = go_annotations[go_id]["namespace"]
```

Post 8/4/16 (after the remediating commit), the code was bumped up to **line 70**.
```
70             namespace = go_annotations[go_id]["namespace"]
```

The error @subinamehta posted shows an error from the previous version.

On that note... If we reinstall it, should we remove the Galaxy Toolshed packages in the [wrapper](https://github.com/ASaiM/galaxytools/blob/master/tools/group_humann2_uniref_abundances_to_GO/tool_dependencies.xml) and use Conda recipes instead? [Here](https://github.com/ASaiM/galaxytools/compare/master...jraysajulga:master) are my proposed changes.

**Comment by bebatut** [comment]
Thanks @jraysajulga for investigating. I did not remember this change...

Yes we should remove the full `tool_dependencies.xml` and use only the conda recipe.
BTW, did you  check if the conda recipe is up to date?

**Comment by jraysajulga** [comment]
@bebatut. The conda recipes are up-to-date if we update Humann2 to 0.11.2. How about the group_abundances script? The conda recipe doesn't seem to work... Should we keep that portion in the tool_dependencies.xml?

**Comment by bebatut** [comment]
`tool_dependencies.xml` file should go away. It is not the recommended way in Galaxy anymore

so we should make the conda recipe work. What is failing for it?

**Comment by jraysajulga** [comment]
```
$ conda install -c bioconda group_humann2_uniref_abundances_to_go
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - group_humann2_uniref_abundances_to_go

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by jraysajulga** [comment]
@bebatut I looked more into it. The Conda recipe is still drawing from version 1.2.0 (has the error described above). So, on the [ASaiM/group_humann2_uniref_abundances_to_GO](https://github.com/ASaiM/group_humann2_uniref_abundances_to_GO) GitHub repo, we should publish another version (ex: 1.2.1) that contains the _UNGROUPED_ fix. Then we can update the Conda recipe ([meta.yaml](https://anaconda.org/bioconda/group_humann2_uniref_abundances_to_go)) to use the updated source: `url: https://github.com/ASaiM/group_humann2_uniref_abundances_to_GO/archive/v1.2.1.zip`
